// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type PageDocumentDataSlicesSlice =
  | FooterNavigationAndServicesRegionsSlice
  | FeaturedCardGridSlice
  | ContentHeaderSlice
  | ContactPanelSlice
  | HeroBannerSlice
  | MenuNavigationSlice
  | AboutSectionSlice
  | WhatWeDoSliceSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/**
 * Primary content in *About Section → Default → Primary*
 */
export interface AboutSectionSliceDefaultPrimary {
  /**
   * Profile Image field in *About Section → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutSection.default.primary.profile_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  profile_image: prismic.ImageField<never>;

  /**
   * Heading field in *About Section → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutSection.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *About Section → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutSection.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * CTA Text field in *About Section → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ready to work together?
   * - **API ID Path**: aboutSection.default.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_text: prismic.KeyTextField;

  /**
   * CTA Button Label field in *About Section → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Get in touch
   * - **API ID Path**: aboutSection.default.primary.cta_button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_button_label: prismic.KeyTextField;

  /**
   * CTA Button Link field in *About Section → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: #contact
   * - **API ID Path**: aboutSection.default.primary.cta_button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for About Section Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard about section with image, heading, and body text.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *About Section*
 */
type AboutSectionSliceVariation = AboutSectionSliceDefault;

/**
 * About Section Shared Slice
 *
 * - **API ID**: `aboutSection`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSectionSlice = prismic.SharedSlice<
  "aboutSection",
  AboutSectionSliceVariation
>;

/**
 * Item in *ContactPanel → Default → Primary → Contact Items*
 */
export interface ContactPanelSliceDefaultPrimaryContactsItem {
  /**
   * Contact Type field in *ContactPanel → Default → Primary → Contact Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_panel.default.primary.contacts[].contact_type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  contact_type: prismic.SelectField<"phone" | "email" | "location">;

  /**
   * Contact Text field in *ContactPanel → Default → Primary → Contact Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_panel.default.primary.contacts[].contact_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_label: prismic.KeyTextField;
}

/**
 * Item in *ContactPanel → Default → Primary → Form Fields*
 */
export interface ContactPanelSliceDefaultPrimaryFormFieldsItem {
  /**
   * Field Label field in *ContactPanel → Default → Primary → Form Fields*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_panel.default.primary.form_fields[].field_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  field_label: prismic.KeyTextField;

  /**
   * Field Type field in *ContactPanel → Default → Primary → Form Fields*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_panel.default.primary.form_fields[].field_type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  field_type: prismic.SelectField<"text" | "email" | "phone" | "textarea">;

  /**
   * Is Required field in *ContactPanel → Default → Primary → Form Fields*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_panel.default.primary.form_fields[].is_required
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_required: prismic.BooleanField;
}

/**
 * Primary content in *ContactPanel → Default → Primary*
 */
export interface ContactPanelSliceDefaultPrimary {
  /**
   * Contact Items field in *ContactPanel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_panel.default.primary.contacts[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  contacts: prismic.GroupField<
    Simplify<ContactPanelSliceDefaultPrimaryContactsItem>
  >;

  /**
   * Title field in *ContactPanel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_panel.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Form Title field in *ContactPanel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_panel.default.primary.form_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  form_title: prismic.RichTextField;

  /**
   * Form Fields field in *ContactPanel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_panel.default.primary.form_fields[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  form_fields: prismic.GroupField<
    Simplify<ContactPanelSliceDefaultPrimaryFormFieldsItem>
  >;

  /**
   * Button Text field in *ContactPanel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_panel.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;
}

/**
 * Default variation for ContactPanel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Basic layout with contact details on one side and a contact form on the other.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactPanelSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactPanelSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactPanel*
 */
type ContactPanelSliceVariation = ContactPanelSliceDefault;

/**
 * ContactPanel Shared Slice
 *
 * - **API ID**: `contact_panel`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactPanelSlice = prismic.SharedSlice<
  "contact_panel",
  ContactPanelSliceVariation
>;

/**
 * Primary content in *Pricing → Centered Title and Subtext → Primary*
 */
export interface ContentHeaderSliceCenteredTitleAndSubtextPrimary {
  /**
   * Title field in *Pricing → Centered Title and Subtext → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_header.centered_title_and_subtext.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Pricing → Centered Title and Subtext → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_header.centered_title_and_subtext.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Background Color field in *Pricing → Centered Title and Subtext → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: content_header.centered_title_and_subtext.primary.background_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  background_color: prismic.ColorField;
}

/**
 * Centered Title and Subtext variation for Pricing Slice
 *
 * - **API ID**: `centered_title_and_subtext`
 * - **Description**: Displays a center-aligned title with a center-aligned supporting description beneath it.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentHeaderSliceCenteredTitleAndSubtext =
  prismic.SharedSliceVariation<
    "centered_title_and_subtext",
    Simplify<ContentHeaderSliceCenteredTitleAndSubtextPrimary>,
    never
  >;

/**
 * Slice variation for *Pricing*
 */
type ContentHeaderSliceVariation = ContentHeaderSliceCenteredTitleAndSubtext;

/**
 * Pricing Shared Slice
 *
 * - **API ID**: `content_header`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentHeaderSlice = prismic.SharedSlice<
  "content_header",
  ContentHeaderSliceVariation
>;

/**
 * Item in *FeaturedCardCarousel → Default → Primary → Cards*
 */
export interface FeaturedCardGridSliceDefaultPrimaryCardsItem {
  /**
   * Logo field in *FeaturedCardCarousel → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_card_grid.default.primary.cards[].logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Title field in *FeaturedCardCarousel → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_card_grid.default.primary.cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description List field in *FeaturedCardCarousel → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_card_grid.default.primary.cards[].description_list
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description_list: prismic.RichTextField;

  /**
   * Link field in *FeaturedCardCarousel → Default → Primary → Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_card_grid.default.primary.cards[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *FeaturedCardCarousel → Default → Primary*
 */
export interface FeaturedCardGridSliceDefaultPrimary {
  /**
   * Section Heading field in *FeaturedCardCarousel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_card_grid.default.primary.section_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_heading: prismic.RichTextField;

  /**
   * Cards field in *FeaturedCardCarousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_card_grid.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<
    Simplify<FeaturedCardGridSliceDefaultPrimaryCardsItem>
  >;
}

/**
 * Default variation for FeaturedCardCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Grid of featured cards with image, title, bullet list, and link.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedCardGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedCardGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeaturedCardCarousel*
 */
type FeaturedCardGridSliceVariation = FeaturedCardGridSliceDefault;

/**
 * FeaturedCardCarousel Shared Slice
 *
 * - **API ID**: `featured_card_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedCardGridSlice = prismic.SharedSlice<
  "featured_card_grid",
  FeaturedCardGridSliceVariation
>;

/**
 * Item in *FooterNavigationAndServicesRegions → Default Footer → Primary → Services by Region*
 */
export interface FooterNavigationAndServicesRegionsSliceDefaultPrimaryServicesRegionsItem {
  /**
   * Service Title field in *FooterNavigationAndServicesRegions → Default Footer → Primary → Services by Region*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation_and_services_regions.default.primary.services_regions[].service_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  service_title: prismic.KeyTextField;

  /**
   * Service region field in *FooterNavigationAndServicesRegions → Default Footer → Primary → Services by Region*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation_and_services_regions.default.primary.services_regions[].service_region
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  service_region: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Primary content in *FooterNavigationAndServicesRegions → Default Footer → Primary*
 */
export interface FooterNavigationAndServicesRegionsSliceDefaultPrimary {
  /**
   * Brand Title field in *FooterNavigationAndServicesRegions → Default Footer → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation_and_services_regions.default.primary.brand_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  brand_title: prismic.KeyTextField;

  /**
   * Brand Subtitle field in *FooterNavigationAndServicesRegions → Default Footer → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation_and_services_regions.default.primary.brand_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  brand_subtitle: prismic.KeyTextField;

  /**
   * Description field in *FooterNavigationAndServicesRegions → Default Footer → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation_and_services_regions.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Navigation Links field in *FooterNavigationAndServicesRegions → Default Footer → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation_and_services_regions.default.primary.navigation_links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  navigation_links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Services by Region field in *FooterNavigationAndServicesRegions → Default Footer → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation_and_services_regions.default.primary.services_regions[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  services_regions: prismic.GroupField<
    Simplify<FooterNavigationAndServicesRegionsSliceDefaultPrimaryServicesRegionsItem>
  >;

  /**
   * Copyright Notice field in *FooterNavigationAndServicesRegions → Default Footer → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation_and_services_regions.default.primary.copyright_notice
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  copyright_notice: prismic.KeyTextField;
}

/**
 * Default Footer variation for FooterNavigationAndServicesRegions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Footer with navigation links, service-region groupings, and copyright notice.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterNavigationAndServicesRegionsSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<FooterNavigationAndServicesRegionsSliceDefaultPrimary>,
    never
  >;

/**
 * Slice variation for *FooterNavigationAndServicesRegions*
 */
type FooterNavigationAndServicesRegionsSliceVariation =
  FooterNavigationAndServicesRegionsSliceDefault;

/**
 * FooterNavigationAndServicesRegions Shared Slice
 *
 * - **API ID**: `footer_navigation_and_services_regions`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterNavigationAndServicesRegionsSlice = prismic.SharedSlice<
  "footer_navigation_and_services_regions",
  FooterNavigationAndServicesRegionsSliceVariation
>;

/**
 * Item in *Hero Banner → Default → Primary → Call To Action*
 */
export interface HeroBannerSliceDefaultPrimaryCtaItem {
  /**
   * Button Label field in *Hero Banner → Default → Primary → Call To Action*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.cta[].cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_label: prismic.KeyTextField;

  /**
   * Button Link field in *Hero Banner → Default → Primary → Call To Action*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.cta[].cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Hero Banner → Default → Primary*
 */
export interface HeroBannerSliceDefaultPrimary {
  /**
   * Background Color (hex or CSS variable) field in *Hero Banner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  background_color: prismic.KeyTextField;

  /**
   * Headline field in *Hero Banner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline: prismic.RichTextField;

  /**
   * Subheadline field in *Hero Banner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.subheadline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subheadline: prismic.RichTextField;

  /**
   * Call To Action field in *Hero Banner → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.cta[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cta: prismic.GroupField<Simplify<HeroBannerSliceDefaultPrimaryCtaItem>>;
}

/**
 * Default variation for Hero Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard hero section with text and button.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero Banner*
 */
type HeroBannerSliceVariation = HeroBannerSliceDefault;

/**
 * Hero Banner Shared Slice
 *
 * - **API ID**: `hero_banner`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroBannerSlice = prismic.SharedSlice<
  "hero_banner",
  HeroBannerSliceVariation
>;

/**
 * Item in *Menu Navigation → Simple with Logo → Primary → Logo Area*
 */
export interface MenuNavigationSliceSimpleWithLogoPrimaryLogoAreaItem {
  /**
   * Main Logo Text field in *Menu Navigation → Simple with Logo → Primary → Logo Area*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_navigation.simple_with_logo.primary.logo_area[].main_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  main_text: prismic.KeyTextField;

  /**
   * Secondary Logo Text field in *Menu Navigation → Simple with Logo → Primary → Logo Area*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_navigation.simple_with_logo.primary.logo_area[].secondary_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondary_text: prismic.KeyTextField;

  /**
   * Highlighted/Italic Text field in *Menu Navigation → Simple with Logo → Primary → Logo Area*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_navigation.simple_with_logo.primary.logo_area[].highlighted_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  highlighted_text: prismic.KeyTextField;
}

/**
 * Item in *Menu Navigation → Simple with Logo → Primary → Menu Links*
 */
export interface MenuNavigationSliceSimpleWithLogoPrimaryMenuLinksItem {
  /**
   * Link Label field in *Menu Navigation → Simple with Logo → Primary → Menu Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_navigation.simple_with_logo.primary.menu_links[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link URL field in *Menu Navigation → Simple with Logo → Primary → Menu Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_navigation.simple_with_logo.primary.menu_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Menu Navigation → Simple with Logo → Primary*
 */
export interface MenuNavigationSliceSimpleWithLogoPrimary {
  /**
   * Logo Area field in *Menu Navigation → Simple with Logo → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_navigation.simple_with_logo.primary.logo_area[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  logo_area: prismic.GroupField<
    Simplify<MenuNavigationSliceSimpleWithLogoPrimaryLogoAreaItem>
  >;

  /**
   * Menu Links field in *Menu Navigation → Simple with Logo → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_navigation.simple_with_logo.primary.menu_links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  menu_links: prismic.GroupField<
    Simplify<MenuNavigationSliceSimpleWithLogoPrimaryMenuLinksItem>
  >;
}

/**
 * Simple with Logo variation for Menu Navigation Slice
 *
 * - **API ID**: `simple_with_logo`
 * - **Description**: A simple vertical navigation layout that includes a logo area (with styled text) and a list of navigation links.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MenuNavigationSliceSimpleWithLogo = prismic.SharedSliceVariation<
  "simple_with_logo",
  Simplify<MenuNavigationSliceSimpleWithLogoPrimary>,
  never
>;

/**
 * Slice variation for *Menu Navigation*
 */
type MenuNavigationSliceVariation = MenuNavigationSliceSimpleWithLogo;

/**
 * Menu Navigation Shared Slice
 *
 * - **API ID**: `menu_navigation`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MenuNavigationSlice = prismic.SharedSlice<
  "menu_navigation",
  MenuNavigationSliceVariation
>;

/**
 * Item in *What We Do Cards → Default → Primary → Feature Cards*
 */
export interface WhatWeDoSliceSliceDefaultPrimaryFeaturesItem {
  /**
   * Feature Title field in *What We Do Cards → Default → Primary → Feature Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: what_we_do_slice.default.primary.features[].feature_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  feature_title: prismic.KeyTextField;

  /**
   * Feature Description field in *What We Do Cards → Default → Primary → Feature Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: what_we_do_slice.default.primary.features[].feature_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  feature_description: prismic.RichTextField;
}

/**
 * Primary content in *What We Do Cards → Default → Primary*
 */
export interface WhatWeDoSliceSliceDefaultPrimary {
  /**
   * Section Title field in *What We Do Cards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: What We Do
   * - **API ID Path**: what_we_do_slice.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Feature Cards field in *What We Do Cards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: what_we_do_slice.default.primary.features[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  features: prismic.GroupField<
    Simplify<WhatWeDoSliceSliceDefaultPrimaryFeaturesItem>
  >;
}

/**
 * Default variation for What We Do Cards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard layout with section title and repeatable feature cards.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhatWeDoSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhatWeDoSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *What We Do Cards*
 */
type WhatWeDoSliceSliceVariation = WhatWeDoSliceSliceDefault;

/**
 * What We Do Cards Shared Slice
 *
 * - **API ID**: `what_we_do_slice`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhatWeDoSliceSlice = prismic.SharedSlice<
  "what_we_do_slice",
  WhatWeDoSliceSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutSectionSlice,
      AboutSectionSliceDefaultPrimary,
      AboutSectionSliceVariation,
      AboutSectionSliceDefault,
      ContactPanelSlice,
      ContactPanelSliceDefaultPrimaryContactsItem,
      ContactPanelSliceDefaultPrimaryFormFieldsItem,
      ContactPanelSliceDefaultPrimary,
      ContactPanelSliceVariation,
      ContactPanelSliceDefault,
      ContentHeaderSlice,
      ContentHeaderSliceCenteredTitleAndSubtextPrimary,
      ContentHeaderSliceVariation,
      ContentHeaderSliceCenteredTitleAndSubtext,
      FeaturedCardGridSlice,
      FeaturedCardGridSliceDefaultPrimaryCardsItem,
      FeaturedCardGridSliceDefaultPrimary,
      FeaturedCardGridSliceVariation,
      FeaturedCardGridSliceDefault,
      FooterNavigationAndServicesRegionsSlice,
      FooterNavigationAndServicesRegionsSliceDefaultPrimaryServicesRegionsItem,
      FooterNavigationAndServicesRegionsSliceDefaultPrimary,
      FooterNavigationAndServicesRegionsSliceVariation,
      FooterNavigationAndServicesRegionsSliceDefault,
      HeroBannerSlice,
      HeroBannerSliceDefaultPrimaryCtaItem,
      HeroBannerSliceDefaultPrimary,
      HeroBannerSliceVariation,
      HeroBannerSliceDefault,
      MenuNavigationSlice,
      MenuNavigationSliceSimpleWithLogoPrimaryLogoAreaItem,
      MenuNavigationSliceSimpleWithLogoPrimaryMenuLinksItem,
      MenuNavigationSliceSimpleWithLogoPrimary,
      MenuNavigationSliceVariation,
      MenuNavigationSliceSimpleWithLogo,
      WhatWeDoSliceSlice,
      WhatWeDoSliceSliceDefaultPrimaryFeaturesItem,
      WhatWeDoSliceSliceDefaultPrimary,
      WhatWeDoSliceSliceVariation,
      WhatWeDoSliceSliceDefault,
    };
  }
}
