// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type AboutDocumentDataSlicesSlice =
  | AboutSectionSlice
  | MenuNavigationSlice
  | HeroBannerSlice
  | FooterNavigationAndServicesRegionsSlice;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice>; /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

type ContactDocumentDataSlicesSlice =
  | MenuNavigationSlice
  | HeroBannerSlice
  | ContactPanelSlice
  | FooterNavigationAndServicesRegionsSlice;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * Slice Zone field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice>; /**
   * Meta Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

type EcommerceDocumentDataSlicesSlice =
  | AboutSectionSlice
  | ProductComparisonSlice
  | HeroBannerSlice;

/**
 * Content for Ecommerce Page documents
 */
interface EcommerceDocumentData {
  /**
   * Slice Zone field in *Ecommerce Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: ecommerce.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<EcommerceDocumentDataSlicesSlice>; /**
   * Meta Title field in *Ecommerce Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: ecommerce.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Ecommerce Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: ecommerce.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Ecommerce Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ecommerce.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Ecommerce Page document from Prismic
 *
 * - **API ID**: `ecommerce`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EcommerceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<EcommerceDocumentData>,
    "ecommerce",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | FooterNavigationAndServicesRegionsSlice
  | FeaturedCardGridSlice
  | ContactPanelSlice
  | HeroBannerSlice
  | MenuNavigationSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<PageDocumentData>, "page", Lang>;

type SeoDocumentDataSlicesSlice =
  | AboutSectionSlice
  | ProductComparisonSlice
  | HeroBannerSlice;

/**
 * Content for SEO Page documents
 */
interface SeoDocumentData {
  /**
   * Slice Zone field in *SEO Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: seo.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<SeoDocumentDataSlicesSlice>; /**
   * Meta Title field in *SEO Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: seo.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *SEO Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: seo.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *SEO Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: seo.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * SEO Page document from Prismic
 *
 * - **API ID**: `seo`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SeoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<SeoDocumentData>, "seo", Lang>;

type WebsitesDocumentDataSlicesSlice =
  | AboutSectionSlice
  | ProductComparisonSlice
  | HeroBannerSlice;

/**
 * Content for Product Page documents
 */
interface WebsitesDocumentData {
  /**
   * Slice Zone field in *Product Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: websites.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<WebsitesDocumentDataSlicesSlice>; /**
   * Meta Title field in *Product Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: websites.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Product Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: websites.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Product Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: websites.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Product Page document from Prismic
 *
 * - **API ID**: `websites`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WebsitesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<WebsitesDocumentData>,
    "websites",
    Lang
  >;

type WorkDocumentDataSlicesSlice =
  | MenuNavigationSlice
  | HeroBannerSlice
  | FeaturedCardGridSlice
  | FooterNavigationAndServicesRegionsSlice;

/**
 * Content for Work documents
 */
interface WorkDocumentData {
  /**
   * Slice Zone field in *Work*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: work.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<WorkDocumentDataSlicesSlice>; /**
   * Meta Title field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: work.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: work.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Work*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: work.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Work document from Prismic
 *
 * - **API ID**: `work`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorkDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<WorkDocumentData>, "work", Lang>;

export type AllDocumentTypes =
  | AboutDocument
  | ContactDocument
  | EcommerceDocument
  | PageDocument
  | SeoDocument
  | WebsitesDocument
  | WorkDocument;

/**
 * Item in *Page Section → Default → Primary → Product*
 */
export interface AboutSectionSliceDefaultPrimaryProductItem {
  /**
   * Inline link field in *Page Section → Default → Primary → Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutSection.default.primary.product[].inline_link
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  inline_link: prismic.KeyTextField;

  /**
   * Heading field in *Page Section → Default → Primary → Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutSection.default.primary.product[].heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *Page Section → Default → Primary → Product*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutSection.default.primary.product[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * CTA Text field in *Page Section → Default → Primary → Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutSection.default.primary.product[].cta_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_text: prismic.KeyTextField;

  /**
   * CTA Link field in *Page Section → Default → Primary → Product*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutSection.default.primary.product[].cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Page Section → Default → Primary*
 */
export interface AboutSectionSliceDefaultPrimary {
  /**
   * Product field in *Page Section → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutSection.default.primary.product[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  product: prismic.GroupField<
    Simplify<AboutSectionSliceDefaultPrimaryProductItem>
  >;
}

/**
 * Default variation for Page Section Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard about section with image, heading, and body text.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Page Section*
 */
type AboutSectionSliceVariation = AboutSectionSliceDefault;

/**
 * Page Section Shared Slice
 *
 * - **API ID**: `aboutSection`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSectionSlice = prismic.SharedSlice<
  "aboutSection",
  AboutSectionSliceVariation
>;

/**
 * Item in *Page Section → Default → Primary → Product*
 */
export interface AboutSectionSliceDefaultPrimaryProductItem {
  /**
   * Inline link field in *Page Section → Default → Primary → Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutSection.default.primary.product[].inline_link
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  inline_link: prismic.KeyTextField;

  /**
   * Heading field in *Page Section → Default → Primary → Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutSection.default.primary.product[].heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *Page Section → Default → Primary → Product*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutSection.default.primary.product[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * CTA Text field in *Page Section → Default → Primary → Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutSection.default.primary.product[].cta_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_text: prismic.KeyTextField;

  /**
   * CTA Link field in *Page Section → Default → Primary → Product*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutSection.default.primary.product[].cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Page Section → Default → Primary*
 */
export interface AboutSectionSliceDefaultPrimary {
  /**
   * Product field in *Page Section → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutSection.default.primary.product[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  product: prismic.GroupField<
    Simplify<AboutSectionSliceDefaultPrimaryProductItem>
  >;
}

/**
 * Default variation for Page Section Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard about section with image, heading, and body text.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Page Section*
 */
type AboutSectionSliceVariation = AboutSectionSliceDefault;

/**
 * Page Section Shared Slice
 *
 * - **API ID**: `aboutSection`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSectionSlice = prismic.SharedSlice<
  "aboutSection",
  AboutSectionSliceVariation
>;

/**
 * Item in *AboutSection → Default → Primary → Masonry Gallery*
 */
export interface AboutSectionSliceDefaultPrimaryMasonryGalleryItem {
  /**
   * Image field in *AboutSection → Default → Primary → Masonry Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.masonry_gallery[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Link field in *AboutSection → Default → Primary → Masonry Gallery*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.masonry_gallery[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Columns field in *AboutSection → Default → Primary → Masonry Gallery*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.masonry_gallery[].columns
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  columns: prismic.NumberField;
}

/**
 * Primary content in *AboutSection → Default → Primary*
 */
export interface AboutSectionSliceDefaultPrimary {
  /**
   * Heading field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Body Paragraph One field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.body_paragraph_one
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body_paragraph_one: prismic.RichTextField;

  /**
   * Body Paragraph Two field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.body_paragraph_two
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body_paragraph_two: prismic.RichTextField;

  /**
   * Body Paragraph Three field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.body_paragraph_three
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body_paragraph_three: prismic.RichTextField;

  /**
   * Masonry Title field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.masonry_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  masonry_title: prismic.KeyTextField;

  /**
   * About Image field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.about_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  about_image: prismic.ImageField<never>;

  /**
   * Masonry Gallery field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.masonry_gallery[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  masonry_gallery: prismic.GroupField<
    Simplify<AboutSectionSliceDefaultPrimaryMasonryGalleryItem>
  >;
}

/**
 * Default variation for AboutSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutSection*
 */
type AboutSectionSliceVariation = AboutSectionSliceDefault;

/**
 * AboutSection Shared Slice
 *
 * - **API ID**: `about_section`
 * - **Description**: AboutSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSectionSlice = prismic.SharedSlice<
  "about_section",
  AboutSectionSliceVariation
>;

/**
 * Item in *ContactPanel → Default → Primary → Contact Items*
 */
export interface ContactPanelSliceDefaultPrimaryContactsItem {
  /**
   * Contact Type field in *ContactPanel → Default → Primary → Contact Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_panel.default.primary.contacts[].contact_type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  contact_type: prismic.SelectField<"phone" | "email" | "location">;

  /**
   * Contact Text field in *ContactPanel → Default → Primary → Contact Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_panel.default.primary.contacts[].contact_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_label: prismic.KeyTextField;
}

/**
 * Item in *ContactPanel → Default → Primary → Form Fields*
 */
export interface ContactPanelSliceDefaultPrimaryFormFieldsItem {
  /**
   * Field Label field in *ContactPanel → Default → Primary → Form Fields*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_panel.default.primary.form_fields[].field_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  field_label: prismic.KeyTextField;

  /**
   * Field Type field in *ContactPanel → Default → Primary → Form Fields*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_panel.default.primary.form_fields[].field_type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  field_type: prismic.SelectField<"text" | "email" | "phone" | "textarea">;

  /**
   * Is Required field in *ContactPanel → Default → Primary → Form Fields*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_panel.default.primary.form_fields[].is_required
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_required: prismic.BooleanField;
}

/**
 * Primary content in *ContactPanel → Default → Primary*
 */
export interface ContactPanelSliceDefaultPrimary {
  /**
   * Title field in *ContactPanel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_panel.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Contact item title field in *ContactPanel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_panel.default.primary.contact_item_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_item_title: prismic.KeyTextField;

  /**
   * Contact Items field in *ContactPanel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_panel.default.primary.contacts[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  contacts: prismic.GroupField<
    Simplify<ContactPanelSliceDefaultPrimaryContactsItem>
  >;

  /**
   * Form Title field in *ContactPanel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_panel.default.primary.form_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  form_title: prismic.RichTextField;

  /**
   * Form Fields field in *ContactPanel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_panel.default.primary.form_fields[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  form_fields: prismic.GroupField<
    Simplify<ContactPanelSliceDefaultPrimaryFormFieldsItem>
  >;

  /**
   * Button Text field in *ContactPanel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_panel.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;
}

/**
 * Default variation for ContactPanel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Basic layout with contact details on one side and a contact form on the other.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactPanelSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactPanelSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactPanel*
 */
type ContactPanelSliceVariation = ContactPanelSliceDefault;

/**
 * ContactPanel Shared Slice
 *
 * - **API ID**: `contact_panel`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactPanelSlice = prismic.SharedSlice<
  "contact_panel",
  ContactPanelSliceVariation
>;

/**
 * Item in *RecentWork → Default → Primary → Cards*
 */
export interface FeaturedCardGridSliceDefaultPrimaryCardsItem {
  /**
   * Logo field in *RecentWork → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_card_grid.default.primary.cards[].logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Title field in *RecentWork → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_card_grid.default.primary.cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description List field in *RecentWork → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_card_grid.default.primary.cards[].description_list
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description_list: prismic.RichTextField;

  /**
   * Link field in *RecentWork → Default → Primary → Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_card_grid.default.primary.cards[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Background color field in *RecentWork → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_card_grid.default.primary.cards[].background_color
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  background_color: prismic.KeyTextField;

  /**
   * Colour field in *RecentWork → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_card_grid.default.primary.cards[].colour
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  colour: prismic.KeyTextField;
}

/**
 * Primary content in *RecentWork → Default → Primary*
 */
export interface FeaturedCardGridSliceDefaultPrimary {
  /**
   * Section Heading field in *RecentWork → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_card_grid.default.primary.section_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_heading: prismic.RichTextField;

  /**
   * Cards field in *RecentWork → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_card_grid.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<
    Simplify<FeaturedCardGridSliceDefaultPrimaryCardsItem>
  >;

  /**
   * CTA Button Label field in *RecentWork → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_card_grid.default.primary.cta_button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_button_label: prismic.KeyTextField;

  /**
   * CTA Button Link field in *RecentWork → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_card_grid.default.primary.cta_button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for RecentWork Slice
 *
 * - **API ID**: `default`
 * - **Description**: Grid of featured cards with image, title, bullet list, and link.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedCardGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedCardGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RecentWork*
 */
type FeaturedCardGridSliceVariation = FeaturedCardGridSliceDefault;

/**
 * RecentWork Shared Slice
 *
 * - **API ID**: `featured_card_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedCardGridSlice = prismic.SharedSlice<
  "featured_card_grid",
  FeaturedCardGridSliceVariation
>;

/**
 * Item in *Footer → Default Footer → Primary → Services by Region*
 */
export interface FooterNavigationAndServicesRegionsSliceDefaultPrimaryServicesRegionsItem {
  /**
   * Service Title field in *Footer → Default Footer → Primary → Services by Region*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation_and_services_regions.default.primary.services_regions[].service_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  service_title: prismic.KeyTextField;

  /**
   * Service region field in *Footer → Default Footer → Primary → Services by Region*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation_and_services_regions.default.primary.services_regions[].service_region
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  service_region: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Primary content in *Footer → Default Footer → Primary*
 */
export interface FooterNavigationAndServicesRegionsSliceDefaultPrimary {
  /**
   * Brand Title field in *Footer → Default Footer → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation_and_services_regions.default.primary.brand_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  brand_title: prismic.KeyTextField;

  /**
   * Brand Subtitle field in *Footer → Default Footer → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation_and_services_regions.default.primary.brand_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  brand_subtitle: prismic.KeyTextField;

  /**
   * Description field in *Footer → Default Footer → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation_and_services_regions.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Navigation Links field in *Footer → Default Footer → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation_and_services_regions.default.primary.navigation_links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  navigation_links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Services by Region field in *Footer → Default Footer → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation_and_services_regions.default.primary.services_regions[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  services_regions: prismic.GroupField<
    Simplify<FooterNavigationAndServicesRegionsSliceDefaultPrimaryServicesRegionsItem>
  >;

  /**
   * Copyright Notice field in *Footer → Default Footer → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation_and_services_regions.default.primary.copyright_notice
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  copyright_notice: prismic.KeyTextField;
}

/**
 * Default Footer variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Footer with navigation links, service-region groupings, and copyright notice.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterNavigationAndServicesRegionsSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<FooterNavigationAndServicesRegionsSliceDefaultPrimary>,
    never
  >;

/**
 * Slice variation for *Footer*
 */
type FooterNavigationAndServicesRegionsSliceVariation =
  FooterNavigationAndServicesRegionsSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer_navigation_and_services_regions`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterNavigationAndServicesRegionsSlice = prismic.SharedSlice<
  "footer_navigation_and_services_regions",
  FooterNavigationAndServicesRegionsSliceVariation
>;

/**
 * Item in *Hero Banner → Default → Primary → Call To Action*
 */
export interface HeroBannerSliceDefaultPrimaryCtaItem {
  /**
   * Button Label field in *Hero Banner → Default → Primary → Call To Action*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.cta[].cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_label: prismic.KeyTextField;

  /**
   * Button Link field in *Hero Banner → Default → Primary → Call To Action*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.cta[].cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Hero Banner → Default → Primary*
 */
export interface HeroBannerSliceDefaultPrimary {
  /**
   * Background Color (hex or CSS variable) field in *Hero Banner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  background_color: prismic.KeyTextField;

  /**
   * Headline field in *Hero Banner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline: prismic.RichTextField;

  /**
   * Subheadline field in *Hero Banner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.subheadline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subheadline: prismic.RichTextField;

  /**
   * Call To Action field in *Hero Banner → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.cta[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cta: prismic.GroupField<Simplify<HeroBannerSliceDefaultPrimaryCtaItem>>;
}

/**
 * Default variation for Hero Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard hero section with text and button.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero Banner*
 */
type HeroBannerSliceVariation = HeroBannerSliceDefault;

/**
 * Hero Banner Shared Slice
 *
 * - **API ID**: `hero_banner`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroBannerSlice = prismic.SharedSlice<
  "hero_banner",
  HeroBannerSliceVariation
>;

/**
 * Item in *Menu Navigation → Simple with Logo → Primary → Logo Area*
 */
export interface MenuNavigationSliceSimpleWithLogoPrimaryLogoAreaItem {
  /**
   * Main Logo Text field in *Menu Navigation → Simple with Logo → Primary → Logo Area*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_navigation.simple_with_logo.primary.logo_area[].main_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  main_text: prismic.KeyTextField;

  /**
   * Secondary Logo Text field in *Menu Navigation → Simple with Logo → Primary → Logo Area*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_navigation.simple_with_logo.primary.logo_area[].secondary_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondary_text: prismic.KeyTextField;

  /**
   * Highlighted/Italic Text field in *Menu Navigation → Simple with Logo → Primary → Logo Area*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_navigation.simple_with_logo.primary.logo_area[].highlighted_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  highlighted_text: prismic.KeyTextField;
}

/**
 * Item in *Menu Navigation → Simple with Logo → Primary → Menu Links*
 */
export interface MenuNavigationSliceSimpleWithLogoPrimaryMenuLinksItem {
  /**
   * Link Label field in *Menu Navigation → Simple with Logo → Primary → Menu Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_navigation.simple_with_logo.primary.menu_links[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link URL field in *Menu Navigation → Simple with Logo → Primary → Menu Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_navigation.simple_with_logo.primary.menu_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Dropdown field in *Menu Navigation → Simple with Logo → Primary → Menu Links*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: menu_navigation.simple_with_logo.primary.menu_links[].dropdown
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  dropdown: prismic.BooleanField;

  /**
   * Dropdown title field in *Menu Navigation → Simple with Logo → Primary → Menu Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_navigation.simple_with_logo.primary.menu_links[].dropdown_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  dropdown_title: prismic.KeyTextField;

  /**
   * Dropdown Link field in *Menu Navigation → Simple with Logo → Primary → Menu Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_navigation.simple_with_logo.primary.menu_links[].dropdown_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  dropdown_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Dropdown title 2 field in *Menu Navigation → Simple with Logo → Primary → Menu Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_navigation.simple_with_logo.primary.menu_links[].dropdown_title_2
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  dropdown_title_2: prismic.KeyTextField;

  /**
   * Dopdown link 2 field in *Menu Navigation → Simple with Logo → Primary → Menu Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_navigation.simple_with_logo.primary.menu_links[].dopdown_link_2
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  dopdown_link_2: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Dropdown title 3 field in *Menu Navigation → Simple with Logo → Primary → Menu Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_navigation.simple_with_logo.primary.menu_links[].dropdown_title_3
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  dropdown_title_3: prismic.KeyTextField;

  /**
   * Dropdown Link 3 field in *Menu Navigation → Simple with Logo → Primary → Menu Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_navigation.simple_with_logo.primary.menu_links[].dropdown_link_3
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  dropdown_link_3: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Menu Navigation → Simple with Logo → Primary*
 */
export interface MenuNavigationSliceSimpleWithLogoPrimary {
  /**
   * Logo Area field in *Menu Navigation → Simple with Logo → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_navigation.simple_with_logo.primary.logo_area[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  logo_area: prismic.GroupField<
    Simplify<MenuNavigationSliceSimpleWithLogoPrimaryLogoAreaItem>
  >;

  /**
   * Menu Links field in *Menu Navigation → Simple with Logo → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_navigation.simple_with_logo.primary.menu_links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  menu_links: prismic.GroupField<
    Simplify<MenuNavigationSliceSimpleWithLogoPrimaryMenuLinksItem>
  >;
}

/**
 * Simple with Logo variation for Menu Navigation Slice
 *
 * - **API ID**: `simple_with_logo`
 * - **Description**: A simple vertical navigation layout that includes a logo area (with styled text) and a list of navigation links.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MenuNavigationSliceSimpleWithLogo = prismic.SharedSliceVariation<
  "simple_with_logo",
  Simplify<MenuNavigationSliceSimpleWithLogoPrimary>,
  never
>;

/**
 * Slice variation for *Menu Navigation*
 */
type MenuNavigationSliceVariation = MenuNavigationSliceSimpleWithLogo;

/**
 * Menu Navigation Shared Slice
 *
 * - **API ID**: `menu_navigation`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MenuNavigationSlice = prismic.SharedSlice<
  "menu_navigation",
  MenuNavigationSliceVariation
>;

/**
 * Item in *ProductComparison → Default → Primary → Product*
 */
export interface ProductComparisonSliceDefaultPrimaryProductItem {
  /**
   * Product Title field in *ProductComparison → Default → Primary → Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_comparison.default.primary.product[].product_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  product_title: prismic.KeyTextField;

  /**
   * Product Brief Description field in *ProductComparison → Default → Primary → Product*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_comparison.default.primary.product[].product_brief_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  product_brief_description: prismic.RichTextField;

  /**
   * Product Inline Link Text field in *ProductComparison → Default → Primary → Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_comparison.default.primary.product[].product_inline_link_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  product_inline_link_text: prismic.KeyTextField;

  /**
   * Product Inline Link field in *ProductComparison → Default → Primary → Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_comparison.default.primary.product[].product_inline_link
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  product_inline_link: prismic.KeyTextField;
}

/**
 * Primary content in *ProductComparison → Default → Primary*
 */
export interface ProductComparisonSliceDefaultPrimary {
  /**
   * Product field in *ProductComparison → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product_comparison.default.primary.product[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  product: prismic.GroupField<
    Simplify<ProductComparisonSliceDefaultPrimaryProductItem>
  >;
}

/**
 * Default variation for ProductComparison Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProductComparisonSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductComparisonSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProductComparison*
 */
type ProductComparisonSliceVariation = ProductComparisonSliceDefault;

/**
 * ProductComparison Shared Slice
 *
 * - **API ID**: `product_comparison`
 * - **Description**: ProductComparison
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProductComparisonSlice = prismic.SharedSlice<
  "product_comparison",
  ProductComparisonSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSlicesSlice,
      EcommerceDocument,
      EcommerceDocumentData,
      EcommerceDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SeoDocument,
      SeoDocumentData,
      SeoDocumentDataSlicesSlice,
      WebsitesDocument,
      WebsitesDocumentData,
      WebsitesDocumentDataSlicesSlice,
      WorkDocument,
      WorkDocumentData,
      WorkDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutSectionSlice,
      AboutSectionSliceDefaultPrimaryProductItem,
      AboutSectionSliceDefaultPrimary,
      AboutSectionSliceVariation,
      AboutSectionSliceDefault,
      AboutSectionSlice,
      AboutSectionSliceDefaultPrimaryProductItem,
      AboutSectionSliceDefaultPrimary,
      AboutSectionSliceVariation,
      AboutSectionSliceDefault,
      AboutSectionSlice,
      AboutSectionSliceDefaultPrimaryMasonryGalleryItem,
      AboutSectionSliceDefaultPrimary,
      AboutSectionSliceVariation,
      AboutSectionSliceDefault,
      ContactPanelSlice,
      ContactPanelSliceDefaultPrimaryContactsItem,
      ContactPanelSliceDefaultPrimaryFormFieldsItem,
      ContactPanelSliceDefaultPrimary,
      ContactPanelSliceVariation,
      ContactPanelSliceDefault,
      FeaturedCardGridSlice,
      FeaturedCardGridSliceDefaultPrimaryCardsItem,
      FeaturedCardGridSliceDefaultPrimary,
      FeaturedCardGridSliceVariation,
      FeaturedCardGridSliceDefault,
      FooterNavigationAndServicesRegionsSlice,
      FooterNavigationAndServicesRegionsSliceDefaultPrimaryServicesRegionsItem,
      FooterNavigationAndServicesRegionsSliceDefaultPrimary,
      FooterNavigationAndServicesRegionsSliceVariation,
      FooterNavigationAndServicesRegionsSliceDefault,
      HeroBannerSlice,
      HeroBannerSliceDefaultPrimaryCtaItem,
      HeroBannerSliceDefaultPrimary,
      HeroBannerSliceVariation,
      HeroBannerSliceDefault,
      MenuNavigationSlice,
      MenuNavigationSliceSimpleWithLogoPrimaryLogoAreaItem,
      MenuNavigationSliceSimpleWithLogoPrimaryMenuLinksItem,
      MenuNavigationSliceSimpleWithLogoPrimary,
      MenuNavigationSliceVariation,
      MenuNavigationSliceSimpleWithLogo,
      ProductComparisonSlice,
      ProductComparisonSliceDefaultPrimaryProductItem,
      ProductComparisonSliceDefaultPrimary,
      ProductComparisonSliceVariation,
      ProductComparisonSliceDefault,
    };
  }
}
