// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  aboutSection: dynamic(() => import("./AboutSection")),
  contact_panel: dynamic(() => import("./ContactPanel")),
  content_header: dynamic(() => import("./Pricing")),
  featured_card_grid: dynamic(() => import("./FeaturedCardCarousel")),
  footer_navigation_and_services_regions: dynamic(
    () => import("./FooterNavigationAndServicesRegions"),
  ),
  hero_banner: dynamic(() => import("./HeroBanner")),
  menu_navigation: dynamic(() => import("./MenuNavigation")),
  what_we_do_slice: dynamic(() => import("./WhatWeDoCards")),
};
