// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  aboutSection: dynamic(() => import("./PageSection")),
  aboutSection: dynamic(() => import("./PageSection")),
  about_section: dynamic(() => import("./AboutSection")),
  contact_panel: dynamic(() => import("./ContactPanel")),
  featured_card_grid: dynamic(() => import("./RecentWork")),
  footer_navigation_and_services_regions: dynamic(() => import("./Footer")),
  hero_banner: dynamic(() => import("./HeroBanner")),
  menu_navigation: dynamic(() => import("./MenuNavigation")),
  product_comparison: dynamic(() => import("./ProductComparison")),
};
